# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
#
sudo: false

## после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
## Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

## Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -mail
    on_success: never # default: change
    on_failure: never # default: always
